"use client";
import React, { createContext, useContext, useState } from 'react';

type Language = 'English' | 'हिंदी' | 'বাংলা' | 'తెలుగు' | 'मराठी' | 'தமிழ்';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isGlobalChatOpen: boolean;
  setIsGlobalChatOpen: (isOpen: boolean | ((prev: boolean) => boolean)) => void;
}

const translations: Record<string, Record<string, string>> = {
  English: {
    skipToMain: 'Skip to Main Content',
    highContrast: 'High Contrast',
    home: 'Home',
    services: 'Services',
    complaints: 'My Complaints',
    resources: 'Resources',
    search: 'Search...',
    profile: 'My Profile',
    settings: 'Settings',
    logout: 'Sign Out',
    citizen: 'Citizen',
    heroBadge: 'Gen AI Powered',
    heroTitle: 'SMART BHARAT',
    heroSubtitle: 'Your intelligent AI companion for government services, issue reporting, and personalized civic support.',
    exploreServices: 'Explore Services',
    trackComplaints: 'Track Complaints',
    featAiTitle: 'AI Assistant',
    featAiDesc: 'Get instant answers to your civic queries.',
    featServTitle: 'Popular Services',
    featServDesc: 'Explore and apply for various government services.',
    featCompTitle: 'Report an Issue',
    featCompDesc: 'Report civic issues in your area and help your community.',
    featSchemeTitle: 'Schemes for You',
    featSchemeDesc: 'Get personalized scheme recommendations that fit your needs.',
    chatGreeting: 'Hello! 👋 How can I help you today? Ask me anything about government services, schemes, documents, or report an issue.',
    chatPlaceholder: 'Type your question...',
    chatTryAsking: 'Try asking:',
    sug1: 'How to get a Birth Certificate?',
    sug2: 'Documents required for PM Awas Yojana?',
    sug3: 'How to report a broken street light?',
    
    // Services Page
    servicesTitle: 'Government Services',
    servicesSubtitle: 'Find, understand, and apply for government services with the help of AI. We simplify the complex procedures for you.',
    servicesSearchPlaceholder: 'Search for a service (e.g., PAN, Aadhar)...',
    servicesAiDetailsBtn: 'AI Details',
    servicesPortalBtn: 'Portal',
    servicesNoResults: 'No services found matching your criteria.',

    // Complaints Page
    complaintsTitle: 'My Complaints',
    complaintsSubtitle: 'Track and manage your civic issue reports.',
    complaintsReportBtn: 'Report New Issue',
    complaintsNoIssues: 'You haven\'t reported any issues yet.',
    complaintsModalTitle: 'Report Civic Issue',
    complaintsFormTitle: 'Issue Title',
    complaintsFormTitleHolder: 'e.g., Water Leakage on Main Street',
    complaintsFormLoc: 'Location / Landmark',
    complaintsFormLocHolder: 'e.g., Near City Hospital, Sector 12',
    complaintsFormDesc: 'Description',
    complaintsFormDescSub: '(Describe the problem in your own words)',
    complaintsFormDescHolder: 'Explain what the issue is, since when it\'s been happening...',
    complaintsAiDraft: '✨ Let AI draft it professionally',
    complaintsAiRewrite: 'Rewrite with AI',
    complaintsSubmit: 'Submit Complaint',
    complaintsCancel: 'Cancel',

    // Resources Page
    resourcesTitle: 'Civic Resources & Schemes',
    resourcesSubtitle: 'Find important information, schemes, and guidelines curated for you.',
    resourcesExploreBtn: 'Explore',
    resourcesDownloadBtn: 'Download'
  },
  'हिंदी': {
    skipToMain: 'मुख्य सामग्री पर जाएं',
    highContrast: 'उच्च कंट्रास्ट',
    home: 'मुख्य पृष्ठ',
    services: 'सेवाएं',
    complaints: 'मेरी शिकायतें',
    resources: 'संसाधन',
    search: 'खोजें...',
    profile: 'मेरी प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    logout: 'साइन आउट',
    citizen: 'नागरिक',
    heroBadge: 'जेन एआई संचालित',
    heroTitle: 'स्मार्ट भारत',
    heroSubtitle: 'सरकारी सेवाओं, समस्या रिपोर्टिंग और व्यक्तिगत नागरिक सहायता के लिए आपका बुद्धिमान एआई साथी।',
    exploreServices: 'सेवाएं एक्सप्लोर करें',
    trackComplaints: 'शिकायतें ट्रैक करें',
    featAiTitle: 'एआई सहायक',
    featAiDesc: 'अपने नागरिक प्रश्नों के त्वरित उत्तर प्राप्त करें।',
    featServTitle: 'लोकप्रिय सेवाएं',
    featServDesc: 'विभिन्न सरकारी सेवाओं का अन्वेषण करें और आवेदन करें।',
    featCompTitle: 'समस्या की रिपोर्ट करें',
    featCompDesc: 'अपने क्षेत्र में नागरिक मुद्दों की रिपोर्ट करें और अपने समुदाय की मदद करें।',
    featSchemeTitle: 'आपके लिए योजनाएं',
    featSchemeDesc: 'व्यक्तिगत योजना सिफारिशें प्राप्त करें जो आपकी आवश्यकताओं के अनुरूप हों।',
    chatGreeting: 'नमस्ते! 👋 आज मैं आपकी कैसे मदद कर सकता हूँ? मुझसे सरकारी सेवाओं, योजनाओं, दस्तावेजों के बारे में पूछें या किसी समस्या की रिपोर्ट करें।',
    chatPlaceholder: 'अपना प्रश्न टाइप करें...',
    chatTryAsking: 'यह पूछने का प्रयास करें:',
    sug1: 'जन्म प्रमाण पत्र कैसे प्राप्त करें?',
    sug2: 'पीएम आवास योजना के लिए आवश्यक दस्तावेज?',
    sug3: 'टूटी हुई स्ट्रीट लाइट की रिपोर्ट कैसे करें?',

    servicesTitle: 'सरकारी सेवाएं',
    servicesSubtitle: 'एआई की मदद से सरकारी सेवाएं खोजें, समझें और आवेदन करें। हम आपके लिए जटिल प्रक्रियाओं को सरल बनाते हैं।',
    servicesSearchPlaceholder: 'सेवा खोजें (जैसे, पैन, आधार)...',
    servicesAiDetailsBtn: 'एआई विवरण',
    servicesPortalBtn: 'पोर्टल',
    servicesNoResults: 'आपके खोज मानदंडों से मेल खाने वाली कोई सेवा नहीं मिली।',

    complaintsTitle: 'मेरी शिकायतें',
    complaintsSubtitle: 'अपने नागरिक मुद्दे की रिपोर्ट ट्रैक करें और प्रबंधित करें।',
    complaintsReportBtn: 'नई समस्या दर्ज करें',
    complaintsNoIssues: 'आपने अभी तक किसी समस्या की रिपोर्ट नहीं की है।',
    complaintsModalTitle: 'नागरिक समस्या दर्ज करें',
    complaintsFormTitle: 'समस्या का शीर्षक',
    complaintsFormTitleHolder: 'उदा. मुख्य सड़क पर पानी का रिसाव',
    complaintsFormLoc: 'स्थान / लैंडमार्क',
    complaintsFormLocHolder: 'उदा. सिटी अस्पताल के पास, सेक्टर 12',
    complaintsFormDesc: 'विवरण',
    complaintsFormDescSub: '(समस्या का अपने शब्दों में वर्णन करें)',
    complaintsFormDescHolder: 'समझाएं कि समस्या क्या है, कब से हो रही है...',
    complaintsAiDraft: '✨ एआई को इसे पेशेवर रूप से ड्राफ्ट करने दें',
    complaintsAiRewrite: 'एआई के साथ फिर से लिखें',
    complaintsSubmit: 'शिकायत दर्ज करें',
    complaintsCancel: 'रद्द करें',

    resourcesTitle: 'नागरिक संसाधन और योजनाएं',
    resourcesSubtitle: 'आपके लिए महत्वपूर्ण जानकारी, योजनाएं और दिशानिर्देश खोजें।',
    resourcesExploreBtn: 'अन्वेषण करें',
    resourcesDownloadBtn: 'डाउनलोड'
  },
  'বাংলা': {
    skipToMain: 'মূল বিষয়বস্তুতে যান',
    highContrast: 'উচ্চ বৈসাদৃশ্য',
    home: 'হোম',
    services: 'পরিষেবা',
    complaints: 'আমার অভিযোগ',
    resources: 'সম্পদ',
    search: 'অনুসন্ধান...',
    profile: 'আমার প্রোফাইল',
    settings: 'সেটিংস',
    logout: 'লগ আউট',
    citizen: 'নাগরিক',
    heroBadge: 'জেন এআই চালিত',
    heroTitle: 'স্মার্ট ভারত',
    heroSubtitle: 'সরকারি পরিষেবা, সমস্যা রিপোর্টিং এবং ব্যক্তিগত নাগরিক সহায়তার জন্য আপনার বুদ্ধিমান এআই সঙ্গী।',
    exploreServices: 'পরিষেবাগুলি অন্বেষণ করুন',
    trackComplaints: 'অভিযোগ ট্র্যাক করুন',
    featAiTitle: 'এআই সহকারী',
    featAiDesc: 'আপনার নাগরিক প্রশ্নের তাত্ক্ষণিক উত্তর পান।',
    featServTitle: 'জনপ্রিয় পরিষেবা',
    featServDesc: 'অন্বেষণ করুন এবং বিভিন্ন সরকারি পরিষেবার জন্য আবেদন করুন।',
    featCompTitle: 'সমস্যা রিপোর্ট করুন',
    featCompDesc: 'আপনার এলাকায় নাগরিক সমস্যার রিপোর্ট করুন এবং সম্প্রদায়কে সাহায্য করুন।',
    featSchemeTitle: 'আপনার জন্য প্রকল্প',
    featSchemeDesc: 'আপনার প্রয়োজন অনুসারে ব্যক্তিগতকৃত স্কিম সুপারিশ পান।',
    chatGreeting: 'নমস্কার! 👋 আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি? আমাকে সরকারি পরিষেবা, স্কিম, নথি সম্পর্কে জিজ্ঞাসা করুন বা কোনও সমস্যার রিপোর্ট করুন।',
    chatPlaceholder: 'আপনার প্রশ্ন টাইপ করুন...',
    chatTryAsking: 'জিজ্ঞাসা করার চেষ্টা করুন:',
    sug1: 'জন্ম শংসাপত্র কীভাবে পাবেন?',
    sug2: 'প্রধানমন্ত্রী আবাস যোজনার জন্য প্রয়োজনীয় নথি?',
    sug3: 'ভাঙা স্ট্রিট লাইটের রিপোর্ট কীভাবে করবেন?',

    servicesTitle: 'সরকারি পরিষেবা',
    servicesSubtitle: 'এআই এর সাহায্যে সরকারি পরিষেবা খুঁজুন, বুঝুন এবং আবেদন করুন।',
    servicesSearchPlaceholder: 'একটি পরিষেবা খুঁজুন...',
    servicesAiDetailsBtn: 'এআই বিবরণ',
    servicesPortalBtn: 'পোর্টাল',
    servicesNoResults: 'কোনো পরিষেবা পাওয়া যায়নি।',

    complaintsTitle: 'আমার অভিযোগ',
    complaintsSubtitle: 'আপনার রিপোর্ট ট্র্যাক করুন।',
    complaintsReportBtn: 'নতুন অভিযোগ',
    complaintsNoIssues: 'আপনি কোনো অভিযোগ করেননি।',
    complaintsModalTitle: 'অভিযোগ দায়ের করুন',
    complaintsFormTitle: 'শিরোনাম',
    complaintsFormTitleHolder: 'যেমন, রাস্তায় জল লিক',
    complaintsFormLoc: 'স্থান',
    complaintsFormLocHolder: 'যেমন, হাসপাতালের কাছে',
    complaintsFormDesc: 'বিবরণ',
    complaintsFormDescSub: '(আপনার নিজের ভাষায় লিখুন)',
    complaintsFormDescHolder: 'সমস্যাটি ব্যাখ্যা করুন...',
    complaintsAiDraft: '✨ এআই দিয়ে পুনরায় লিখুন',
    complaintsAiRewrite: 'এআই দিয়ে লিখুন',
    complaintsSubmit: 'জমা দিন',
    complaintsCancel: 'বাতিল',

    resourcesTitle: 'নাগরিক সম্পদ ও প্রকল্প',
    resourcesSubtitle: 'গুরুত্বপূর্ণ তথ্য এবং স্কিম খুঁজুন।',
    resourcesExploreBtn: 'অন্বেষণ',
    resourcesDownloadBtn: 'ডাউনলোড'
  },
  'తెలుగు': {
    skipToMain: 'ప్రధాన కంటెంట్‌కు దాటవేయి',
    highContrast: 'అధిక కాంట్రాస్ట్',
    home: 'హోమ్',
    services: 'సేవలు',
    complaints: 'నా ఫిర్యాదులు',
    resources: 'వనరులు',
    search: 'శోధించండి...',
    profile: 'నా ప్రొఫైల్',
    settings: 'సెట్టింగులు',
    logout: 'సైన్ అవుట్',
    citizen: 'పౌరుడు',
    heroBadge: 'జెన్ ఏఐ పవర్డ్',
    heroTitle: 'స్మార్ట్ భారత్',
    heroSubtitle: 'ప్రభుత్వ సేవలు, సమస్య నివేదన మరియు వ్యక్తిగతీకరించిన పౌర మద్దతు కోసం మీ తెలివైన AI సహచరుడు.',
    exploreServices: 'సేవలను అన్వేషించండి',
    trackComplaints: 'ఫిర్యాదులను ట్రాక్ చేయండి',
    featAiTitle: 'ఏఐ అసిస్టెంట్',
    featAiDesc: 'మీ పౌర ప్రశ్నలకు తక్షణ సమాధానాలు పొందండి.',
    featServTitle: 'ప్రసిద్ధ సేవలు',
    featServDesc: 'వివిధ ప్రభుత్వ సేవలను అన్వేషించండి మరియు దరఖాస్తు చేయండి.',
    featCompTitle: 'సమస్యను నివేదించండి',
    featCompDesc: 'మీ ప్రాంతంలోని పౌర సమస్యలను నివేదించండి మరియు మీ సంఘానికి సహాయం చేయండి.',
    featSchemeTitle: 'మీ కోసం పథకాలు',
    featSchemeDesc: 'మీ అవసరాలకు సరిపోయే వ్యక్తిగతీకరించిన పథకం సిఫార్సులను పొందండి.',
    chatGreeting: 'నమస్తే! 👋 ఈ రోజు నేను మీకు ఎలా సహాయపడగలను? ప్రభుత్వ సేవలు, పథకాలు, పత్రాల గురించి నన్ను అడగండి లేదా సమస్యను నివేదించండి.',
    chatPlaceholder: 'మీ ప్రశ్నను టైప్ చేయండి...',
    chatTryAsking: 'అడగడానికి ప్రయత్నించండి:',
    sug1: 'జనన ధృవీకరణ పత్రం ఎలా పొందాలి?',
    sug2: 'పీఎం ఆవాస్ యోజన కోసం కావాల్సిన పత్రాలు?',
    sug3: 'విరిగిన వీధిలైట్ గురించి ఎలా ఫిర్యాదు చేయాలి?',

    servicesTitle: 'ప్రభుత్వ సేవలు',
    servicesSubtitle: 'AI సహాయంతో ప్రభుత్వ సేవలను కనుగొనండి, అర్థం చేసుకోండి మరియు దరఖాస్తు చేయండి.',
    servicesSearchPlaceholder: 'సేవ కోసం శోధించండి...',
    servicesAiDetailsBtn: 'AI వివరాలు',
    servicesPortalBtn: 'పోర్టల్',
    servicesNoResults: 'ఎటువంటి సేవలు కనుగొనబడలేదు.',

    complaintsTitle: 'నా ఫిర్యాదులు',
    complaintsSubtitle: 'మీ ఫిర్యాదులను ట్రాక్ చేయండి.',
    complaintsReportBtn: 'కొత్త ఫిర్యాదు',
    complaintsNoIssues: 'మీరు ఇంకా ఫిర్యాదు చేయలేదు.',
    complaintsModalTitle: 'ఫిర్యాదు నమోదు చేయండి',
    complaintsFormTitle: 'శీర్షిక',
    complaintsFormTitleHolder: 'ఉదా. రోడ్డుపై నీరు',
    complaintsFormLoc: 'స్థలం',
    complaintsFormLocHolder: 'ఉదా. ఆసుపత్రి దగ్గర',
    complaintsFormDesc: 'వివరణ',
    complaintsFormDescSub: '(మీ స్వంత మాటల్లో వ్రాయండి)',
    complaintsFormDescHolder: 'సమస్యను వివరించండి...',
    complaintsAiDraft: '✨ AI తో తిరిగి వ్రాయండి',
    complaintsAiRewrite: 'AI తో వ్రాయండి',
    complaintsSubmit: 'సమర్పించండి',
    complaintsCancel: 'రద్దు',

    resourcesTitle: 'పౌర వనరులు మరియు పథకాలు',
    resourcesSubtitle: 'ముఖ్యమైన సమాచారం మరియు పథకాలను కనుగొనండి.',
    resourcesExploreBtn: 'అన్వేషించండి',
    resourcesDownloadBtn: 'డౌన్‌లోడ్'
  },
  'मराठी': {
    skipToMain: 'मुख्य आशयावर जा',
    highContrast: 'उच्च कॉन्ट्रास्ट',
    home: 'मुख्यपृष्ठ',
    services: 'सेवा',
    complaints: 'माझ्या तक्रारी',
    resources: 'संसाधने',
    search: 'शोधा...',
    profile: 'माझी प्रोफाइल',
    settings: 'सेटिंग्ज',
    logout: 'साइन आउट',
    citizen: 'नागरिक',
    heroBadge: 'जेन एआय समर्थित',
    heroTitle: 'स्मार्ट भारत',
    heroSubtitle: 'सरकारी सेवा, समस्या रिपोर्टिंग आणि वैयक्तिकृत नागरी समर्थनासाठी आपला बुद्धिमान एआय सहकारी.',
    exploreServices: 'सेवा एक्सप्लोर करा',
    trackComplaints: 'तक्रारींचा मागोवा घ्या',
    featAiTitle: 'एआय सहाय्यक',
    featAiDesc: 'तुमच्या नागरी प्रश्नांची त्वरित उत्तरे मिळवा.',
    featServTitle: 'लोकप्रिय सेवा',
    featServDesc: 'विविध सरकारी सेवांचे अन्वेषण करा आणि अर्ज करा.',
    featCompTitle: 'समस्येची तक्रार करा',
    featCompDesc: 'तुमच्या क्षेत्रातील नागरी समस्यांची तक्रार करा आणि समुदायाला मदत करा.',
    featSchemeTitle: 'तुमच्यासाठी योजना',
    featSchemeDesc: 'तुमच्या गरजा पूर्ण करणाऱ्या वैयक्तिकृत योजना शिफारसी मिळवा.',
    chatGreeting: 'नमस्कार! 👋 आज मी तुम्हाला कशी मदत करू शकतो? मला सरकारी सेवा, योजना, कागदपत्रांबद्दल विचारा किंवा समस्येची तक्रार करा.',
    chatPlaceholder: 'तुमचा प्रश्न टाईप करा...',
    chatTryAsking: 'हे विचारण्याचा प्रयत्न करा:',
    sug1: 'जन्म प्रमाणपत्र कसे मिळवायचे?',
    sug2: 'पीएम आवास योजनेसाठी आवश्यक कागदपत्रे?',
    sug3: 'तुटलेल्या स्ट्रीट लाईटची तक्रार कशी करावी?',

    servicesTitle: 'सरकारी सेवा',
    servicesSubtitle: 'AI च्या मदतीने सरकारी सेवा शोधा, समजून घ्या आणि अर्ज करा.',
    servicesSearchPlaceholder: 'सेवा शोधा...',
    servicesAiDetailsBtn: 'AI तपशील',
    servicesPortalBtn: 'पोर्टल',
    servicesNoResults: 'कोणत्याही सेवा आढळल्या नाहीत.',

    complaintsTitle: 'माझ्या तक्रारी',
    complaintsSubtitle: 'तुमच्या तक्रारी ट्रॅक करा.',
    complaintsReportBtn: 'नवीन तक्रार',
    complaintsNoIssues: 'तुम्ही अजून कोणतीही तक्रार नोंदवली नाही.',
    complaintsModalTitle: 'तक्रार नोंदवा',
    complaintsFormTitle: 'शीर्षक',
    complaintsFormTitleHolder: 'उदा. रस्त्यावरील पाणी',
    complaintsFormLoc: 'ठिकाण',
    complaintsFormLocHolder: 'उदा. रुग्णालयाजवळ',
    complaintsFormDesc: 'तपशील',
    complaintsFormDescSub: '(तुमच्या स्वतःच्या शब्दात लिहा)',
    complaintsFormDescHolder: 'समस्या स्पष्ट करा...',
    complaintsAiDraft: '✨ AI सह पुन्हा लिहा',
    complaintsAiRewrite: 'AI सह लिहा',
    complaintsSubmit: 'सबमिट करा',
    complaintsCancel: 'रद्द करा',

    resourcesTitle: 'नागरी संसाधने आणि योजना',
    resourcesSubtitle: 'महत्त्वाची माहिती आणि योजना शोधा.',
    resourcesExploreBtn: 'अन्वेषण करा',
    resourcesDownloadBtn: 'डाउनलोड'
  },
  'தமிழ்': {
    skipToMain: 'முக்கிய உள்ளடக்கத்திற்குச் செல்',
    highContrast: 'உயர் மாறுபாடு',
    home: 'முகப்பு',
    services: 'சேவைகள்',
    complaints: 'என் புகார்கள்',
    resources: 'வளங்கள்',
    search: 'தேடல்...',
    profile: 'என் சுயவிவரம்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    citizen: 'குடிமகன்',
    heroBadge: 'ஜென் AI மூலம் இயங்குகிறது',
    heroTitle: 'ஸ்மார்ட் பாரத்',
    heroSubtitle: 'அரசு சேவைகள், சிக்கல் புகாரளிப்பு மற்றும் தனிப்பயனாக்கப்பட்ட குடிமக்கள் ஆதரவுக்கான உங்கள் அறிவார்ந்த AI தோழர்.',
    exploreServices: 'சேவைகளை ஆராயுங்கள்',
    trackComplaints: 'புகார்களைக் கண்காணிக்கவும்',
    featAiTitle: 'AI உதவியாளர்',
    featAiDesc: 'உங்கள் குடிமை வினவல்களுக்கு உடனடி பதில்களைப் பெறுங்கள்.',
    featServTitle: 'பிரபலமான சேவைகள்',
    featServDesc: 'பல்வேறு அரசு சேவைகளை ஆராய்ந்து விண்ணப்பிக்கவும்.',
    featCompTitle: 'ஒரு சிக்கலைப் புகாரளிக்கவும்',
    featCompDesc: 'உங்கள் பகுதியில் உள்ள குடிமை பிரச்சினைகளைப் புகாரளித்து உங்கள் சமூகத்திற்கு உதவுங்கள்.',
    featSchemeTitle: 'உங்களுக்கான திட்டங்கள்',
    featSchemeDesc: 'உங்கள் தேவைகளுக்கு ஏற்ற தனிப்பயனாக்கப்பட்ட திட்ட பரிந்துரைகளைப் பெறுங்கள்.',
    chatGreeting: 'வணக்கம்! 👋 இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்? அரசு சேவைகள், திட்டங்கள், ஆவணங்கள் பற்றி என்னிடம் கேளுங்கள் அல்லது ஒரு சிக்கலைப் புகாரளிக்கவும்.',
    chatPlaceholder: 'உங்கள் கேள்வியைத் தட்டச்சு செய்க...',
    chatTryAsking: 'இவற்றைக் கேட்க முயற்சிக்கவும்:',
    sug1: 'பிறப்புச் சான்றிதழை எப்படிப் பெறுவது?',
    sug2: 'பிரதமர் ஆவாஸ் யோஜனாவுக்கு தேவையான ஆவணங்கள்?',
    sug3: 'உடைந்த தெரு விளக்கு பற்றி எப்படி புகாரளிப்பது?',

    servicesTitle: 'அரசு சேவைகள்',
    servicesSubtitle: 'AI இன் உதவியுடன் அரசு சேவைகளைக் கண்டறியவும், புரிந்து கொள்ளவும், விண்ணப்பிக்கவும்.',
    servicesSearchPlaceholder: 'சேவையைத் தேடு...',
    servicesAiDetailsBtn: 'AI விவரங்கள்',
    servicesPortalBtn: 'போர்டல்',
    servicesNoResults: 'சேவைகள் எதுவும் கிடைக்கவில்லை.',

    complaintsTitle: 'என் புகார்கள்',
    complaintsSubtitle: 'உங்கள் புகார்களைக் கண்காணிக்கவும்.',
    complaintsReportBtn: 'புதிய புகார்',
    complaintsNoIssues: 'நீங்கள் இன்னும் எந்தப் புகாரும் செய்யவில்லை.',
    complaintsModalTitle: 'புகார் பதிவு செய்',
    complaintsFormTitle: 'தலைப்பு',
    complaintsFormTitleHolder: 'உதாரணமாக. தண்ணீர் கசிவு',
    complaintsFormLoc: 'இடம்',
    complaintsFormLocHolder: 'உதாரணமாக. மருத்துவமனைக்கு அருகில்',
    complaintsFormDesc: 'விவரம்',
    complaintsFormDescSub: '(உங்கள் சொந்த வார்த்தைகளில் எழுதவும்)',
    complaintsFormDescHolder: 'சிக்கலை விளக்குங்கள்...',
    complaintsAiDraft: '✨ AI உடன் மீண்டும் எழுதுங்கள்',
    complaintsAiRewrite: 'AI உடன் எழுது',
    complaintsSubmit: 'சமர்ப்பி',
    complaintsCancel: 'ரத்துசெய்',

    resourcesTitle: 'குடிமை வளங்கள் மற்றும் திட்டங்கள்',
    resourcesSubtitle: 'முக்கியமான தகவல் மற்றும் திட்டங்களைக் கண்டறியவும்.',
    resourcesExploreBtn: 'ஆராயுங்கள்',
    resourcesDownloadBtn: 'பதிவிறக்கு'
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'English',
  setLanguage: () => {},
  t: (key) => key,
  isGlobalChatOpen: false,
  setIsGlobalChatOpen: () => {},
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('English');
  const [isGlobalChatOpen, setIsGlobalChatOpen] = useState(false);

  const t = (key: string) => {
    return translations[language]?.[key] || translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isGlobalChatOpen, setIsGlobalChatOpen }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
